import Mathlib.Tactic.Basic

inductive Player : Type
-- Simple and exhaustive definition of the two players.
| one
| two

open Player

inductive Game : Type 1
-- `Type 1` is used because our node will contain an arbitrary type `α` (which lives in `Type 0`).
-- This is the "bottom-up" definition. No need to prove that the height is finite,
-- the `inductive` keyword guarantees to the compiler that there are no infinite branches.

-- BASE CASE: The game is finished.
-- Crucial remark: There is no "Draw". This line forces the game
-- to be strictly binary (Victory for player 1 or 2).
| leaf : Player → Game

-- INDUCTIVE CASE: The game continues (a node of the tree).
-- It takes 3 fundamental parameters:
-- 1. `Player`: Whose turn is it to play?
-- 2. `(α : Type)`: The set of legal moves available at this precise moment.
-- 3. `(α → Game)`: The "engine" of the game. A lazy evaluation function.
-- "Give me a move `a` of type `α`, and I will generate the next game state for you".
| node : Player → (α : Type) → (α → Game) → Game


def has_winning_strategy : Player → Game → Prop
-- This function evaluates whether a player `p` has an infallible strategy for game `g`.
-- It returns a logical Proposition (`Prop`: True or False).

-- If we are on a leaf, player `p` has a winning strategy if and only if
-- they are the one declared as the winner by the leaf.
| p, Game.leaf winner => p = winner

-- If it is Player 1's turn to play, and we evaluate Player 1's victory:
-- It suffices that THERE EXISTS (∃) at least ONE move `m` in `α` chosen by Player 1,
-- which leads to a game state where Player 1 has a winning strategy.
| one, Game.node one α moves => ∃ m : α, has_winning_strategy one (moves m)

-- If it is Player 2's turn to play, but we evaluate Player 1's victory:
-- We need THAT FOR ALL (∀) moves `m` in `α` chosen by Player 2,
-- lead to a game state where Player 1 has a winning strategy.
| one, Game.node two α moves => ∀ m : α, has_winning_strategy one (moves m)

-- Strict symmetry for Player 2 mutatis mutandis:
| two, Game.node two α moves => ∃ m : α, has_winning_strategy two (moves m)
| two, Game.node one α moves => ∀ m : α, has_winning_strategy two (moves m)


-- Activation of classical logic (law of excluded middle) necessary to proceed by contradiction.
open Classical

-- ==========================================
-- 4. ZERMELO'S THEOREM
-- ==========================================
-- "For any finite game, either Player 1 has a winning strategy or Player 2 does."
theorem zermelo (g : Game) : has_winning_strategy one g ∨ has_winning_strategy two g := by
  -- Structural induction: we tell Lean to prove the theorem from bottom to top.
  -- This replaces the cumbersome "reverse recursion on height h" from your book.
  induction g with
  
  -- CASE 1: We are on a leaf.
  | leaf winner =>
    -- We look at who is the winner.
    cases winner
    · left; rfl  -- If it's 1, the left side of "Or" (∨) is true.
    · right; rfl -- If it's 2, the right side of "Or" (∨) is true.
  
  -- CASE 2: We are on a node.
  -- `ih` (induction hypothesis) contains the vital information:
  -- Lean ASSUMES the theorem is already true for all sub-games generated by `moves`.
  | node turn α moves ih =>
    -- We separate cases based on whose turn it is.
    cases turn
    
    -- Sub-case 2.A: It is Player 1's turn.
    · 
      -- Use of the law of excluded middle: Either 1 has a winning move or doesn't.
      by_cases h : ∃ m, has_winning_strategy one (moves m)
      · left      -- If they have a winning move, Player 1 wins (trivial case).
        exact h
      · right     -- If not, Player 2 wins. Here is the proof:
        intro m   -- "No matter what move `m` Player 1 attempts..."
        -- We look at the induction hypothesis for this specific move `m`.
        cases ih m with
        | inl w1 => 
          -- This is impossible. If 1 won here, `h` would have been true above.
          exfalso 
          exact h ⟨m, w1⟩
        | inr w2 => 
          -- So it must be that 2 has the winning strategy for this sub-game.
          exact w2
    
    -- Sub-case 2.B: It is Player 2's turn (The logic is exactly reversed).
    · 
      by_cases h : ∃ m, has_winning_strategy two (moves m)
      · right
        exact h
      · left
        intro m
        cases ih m with
        | inl w1 =>
          exact w1
        | inr w2 =>
          exfalso
          exact h ⟨m, w2⟩


-- We can also add that both players cannot have a winning strategy at the same time.
lemma no_both_players_win (g : Game) : ¬ (has_winning_strategy one g ∧ has_winning_strategy two g) := by
  intro h
  cases h with
  | intro w1 w2 =>
    -- We use Zermelo's proof to find a contradiction.
    cases zermelo g with
    | inl w1' =>
      -- If 1 has a winning strategy, then 2 cannot have one.
      exact w2 w1'
    | inr w2' =>
      -- If 2 has a winning strategy, then 1 cannot have one.
      exact w1 w2'